name: User Docs test
on: 
   workflow_dispatch:
   pull_request:

jobs:
  runner-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Docker#
        run: docker run -v "$(pwd):/srv_root/docs"  -p "8000:8000" -e ENABLED_HTMLPROOFER=True -e SITE_URL=https://cloud.denbi.de/wiki/ --entrypoint="mkdocs" denbicloud/mkdocswebhook:2.5.0 build -f /srv_root/docs/config.yml
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: ${{ failure() }}
        with:
          type: ${{ job.status }}
          job_name: ':kermit_typing: *Wiki Check*'
          mention_if: 'failure'
          mention: 'To see the error, click on the workflow link and check in which step the workflow failed!  -  '
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          commit: true
          token: ${{secrets.CLOUD_USER_DOCS_WIKI_CHECK}}    
